### ISSUE TITLE
Error occured

### ISSUE THREAD

**Issue by rdehuyss** [burakince/Cake.DependencyCheck#1]
When embedding this Cake plugin, I receive the following error...

========================================
Dependency-Check
========================================
An error occurred when executing task 'Dependency-Check'.
Error: One or more errors occurred.
        Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of
its dependencies. The system cannot find the file specified.

**Comment by burakince** [comment]
Hi Ronald,
Could you send this informations?

OS version: ?
(.Net or .Net Core or Mono) version: ?

**Comment by rdehuyss** [comment]
Hi,

first of all, thanks for the swift response.

Using Windows 10 enterprise, version 1607 and .NET 4.7. Also using the latest cake (0.25.0).

If there is any other info I can provide you, just drop me a note. Would be really handy to have the dependencycheck inside cake build.

**Comment by burakince** [comment]
Hi Ronald,

Could you try again with version 1.1.0? If it throws exception again, please rerun your build with verbose mode and paste logs. (like this -> .\build.ps1 -Verbosity Diagnostic)

I'm using reflection in ArgumentAppender.cs file. So when it call settings.GetType().GetProperties() line, it using System.Reflection.TypeExtensions assembly file and if your system hasn't netstandard1.6 framework it throw System.IO.FileNotFoundException. So I added net4.5 and net4.6 frameworks as my target frameworks. It should work now. :)

Thanks,
Burak

**Comment by burakince** [comment]
Do you get another error again, or can I close this issue?

**Comment by rdehuyss** [comment]
Works like a charm! Excellent work, thank you!

We are going to .net core 2.1 in the middle of next week, will it also support this framework?

**Comment by burakince** [comment]
It's already supported. :)
