### ISSUE TITLE
Update needed for newer Cake version

### ISSUE THREAD

**Issue by frosch95** [burakince/Cake.DependencyCheck#6]
### What version of Cake are you using?
Version 0.30.0+Branch.main.Sha.cab58db40b02346e562531be27fcaa5ea51a3312

### Are you running on a 32 or 64 bit system?
64 bit

### What framework version are you use?  Mono 5.8? .NetCore 2.0? .Net 4.5? .Net 4.6? .Net 4.7?
 .NetCore 2.0

### What environment are you running on? Windows? Linux? Mac?
Windows 10

### How Did You Get This To Happen? (Steps to Reproduce)

With the following code in Task I could not run DependencyCheck without suppressing the cake version verification. 

DependencyCheck(new DependencyCheckSettings
        {
            Project = "TestCenter",
            Scan = "../src",
            Format = "HTML",
			ProxyServer = parameters.ProxyServer,
			ProxyPort = parameters.ProxyPort,
			// NOT SUPPORTED IN THIS VERSION
			DisableNodeJS = true,
			DisableNSP = true,
			DisableNuspec = false
        });

### Output Log

Error: The assembly 'Cake.DependencyCheck, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly must reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by SSANSH** [comment]
+1

**Comment by CRuppert** [comment]
+1
